### ISSUE TITLE
kinect recording rig?

### ISSUE THREAD

**Issue by j2l** [mpalmer0028/BlenderKinectAnimationTools#1]
Hello,
I think it misses the kinect rig you use since everything is hard coded, like `Hips`, ...
Could you please share the rig you use?

**Comment by mpalmer0028** [comment]
Oh sorry, this addon is to help automate the process in these tutorials https://youtube.com/playlist?list=PLZpDYt0cyiuvd2X6ucSYilKJD6rKK2Uys The first 3 or 4 should help you get the data from the Kinect into blender. I'll try to get an example rig and better documentation pushed tonight for this.

**Comment by mpalmer0028** [comment]
Just pushed updated documentation. Hopefully will that tutorial and the steps you should be set

**Comment by j2l** [comment]
Thank you @mpalmer0028 
Ah yes, I remember your Brenda! :)
You blew my mind last year. 

My kinect sensor doesn't give this kind of result quality. In the end, usually feet slip and rotate around root (despite looking good while recording, I guess all axis are rotating), head doesn't rotate without the bust (rotations in general, like wrist, are not working well) and everything is leaning 30° in front of camera. and the rigify rig doesn't have your nice controllers. :smiling_face_with_tear: 

But your add-on works very well. I close this non-existing issue.
Thank you again!

**Comment by mpalmer0028** [comment]
No worries. Yeah, I'm sorry that your captures aren't very good. I've been trying to use a blue plastic tarp as a background similar to a green screen and that seems to help the capture but I have a lot of issues too. Unfortunately the Kinect just has a lot of garbage data when it comes to some of the bones, ones like the wrists and feet have to be animated manually because the they can just bounce around randomly in most of the recordings. I've gotten this to work pretty well with small animations that I can do many takes of, but I've never had enough luck to make anything >30 second to work well. 

Good luck though, the motion capture is cool when the sensor is working.

**Comment by j2l** [comment]
You're right.
Quick question: Your addon only works with the metarig, right? Not the generated rig?

**Comment by mpalmer0028** [comment]
Yeah, it only works for metarigs unfortunately. Metarigs have been good for my uses in Unity, but I think it would have some conflicts with the IK setup on the generated rig, it should be possible to drive a generated rig with the Kinect data if you copy the constraints similar to the addon, but some of the rigs constraints will probably need to be disabled when you want to target the Kinect rig. That tutorial series explains all the constraints you would need for any rig, so you might be able to follow that to make a generic generated rig one that you can reuse.

**Comment by j2l** [comment]
Thank you again @mpalmer0028 
I understand the limitations.
